# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d660bcd6016608036a6f998932399d21f68e35bb9958add95bca2498dbfd4c97c1499241b235fe7bdc2de0ee47e83429d9e86cb346e49c300c50baa571a16cd0

test:
  secret_key_base: b9f781310cfa410280a5f3f8a6d0cad652b2be99f24149272fc0223f7f633bed1ead705a7b53a369b72648e2fd2bdc0d98a757f678ddb81c9a6e1a5afcab88cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
